/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './start-routes/__root'
import { Route as IndexRouteImport } from './start-routes/index'
import { Route as SplatRouteImport } from './start-routes/$'
import { Route as AboutRouteImport } from './start-routes/about'
import { Route as ApplyRouteImport } from './start-routes/apply'
import { Route as ContactRouteImport } from './start-routes/contact'
import { Route as GamesRouteImport } from './start-routes/games'
import { Route as HomeControlRouteImport } from './start-routes/home-control'
import { Route as LicensesRouteImport } from './start-routes/licenses'
import { Route as MapRouteImport } from './start-routes/map'
import { Route as PrivacyRouteImport } from './start-routes/privacy'
import { Route as ProjectsRouteImport } from './start-routes/projects'
import { Route as TermsRouteImport } from './start-routes/terms'
import { Route as ToolsRouteImport } from './start-routes/tools'
import { Route as WsolverRouteImport } from './start-routes/wsolver'
import { Route as ApiJevRouteImport } from './start-routes/api_.jev'
import { Route as ApiNextRouteImport } from './start-routes/api_.next'
import { Route as ApiSmanageRouteImport } from './start-routes/api_.smanage'
import { Route as AuthLogoutRouteImport } from './start-routes/auth_.logout'
import { Route as GamesUmigameRouteImport } from './start-routes/games_.umigame'
import { Route as MapSplatRouteImport } from './start-routes/map_.$'
import { Route as ToolsJevRouteImport } from './start-routes/tools_.jev'
import { Route as ToolsWsolverRouteImport } from './start-routes/tools_.wsolver'
import { Route as ApiDiscordInteractionsRouteImport } from './start-routes/api_.discord_.interactions'
import { Route as ApiHomeShutdownRouteImport } from './start-routes/api_.home_.shutdown'
import { Route as ApiHomeStatusRouteImport } from './start-routes/api_.home_.status'
import { Route as ApiHomeWakeRouteImport } from './start-routes/api_.home_.wake'
import { Route as ApiJevLoginRouteImport } from './start-routes/api_.jev_.login'
import { Route as ApiMcLinkCodesRouteImport } from './start-routes/api_.mc_.link-codes'
import { Route as ApiMcLinkStatusRouteImport } from './start-routes/api_.mc_.link-status'
import { Route as ApiMcStatusRouteImport } from './start-routes/api_.mc_.status'
import { Route as ApiMcUnlinkRouteImport } from './start-routes/api_.mc_.unlink'
import { Route as ApiUmigamePuzzlesRouteImport } from './start-routes/api_.umigame_.puzzles'
import { Route as AuthAccessLoginRouteImport } from './start-routes/auth_.access_.login'
import { Route as AuthAccessLogoutRouteImport } from './start-routes/auth_.access_.logout'
import { Route as AuthAccessStartRouteImport } from './start-routes/auth_.access_.start'
import { Route as AuthDiscordCallbackRouteImport } from './start-routes/auth_.discord_.callback'
import { Route as AuthDiscordStartRouteImport } from './start-routes/auth_.discord_.start'
import { Route as GamesUmigameAboutRouteImport } from './start-routes/games_.umigame_.about'
import { Route as GamesUmigameAdminRouteImport } from './start-routes/games_.umigame_.admin'
import { Route as GamesUmigameFavoritesRouteImport } from './start-routes/games_.umigame_.favorites'
import { Route as GamesUmigameLicensesRouteImport } from './start-routes/games_.umigame_.licenses'
import { Route as GamesUmigameNewRouteImport } from './start-routes/games_.umigame_.new'
import { Route as GamesUmigameRankingsRouteImport } from './start-routes/games_.umigame_.rankings'
import { Route as GamesUmigameRecommendRouteImport } from './start-routes/games_.umigame_.recommend'
import { Route as GamesUmigameResultsRouteImport } from './start-routes/games_.umigame_.results'
import { Route as ApiUmigamePuzzlesIdRouteImport } from './start-routes/api_.umigame_.puzzles_.$id'
import { Route as GamesUmigameAdminJevRouteImport } from './start-routes/games_.umigame_.admin_.jev'
import { Route as GamesUmigameAuthorQualityRouteImport } from './start-routes/games_.umigame_.author_.quality'
import { Route as GamesUmigamePIdRouteImport } from './start-routes/games_.umigame_.p_.$id'
import { Route as GamesUmigameSettingsProfileRouteImport } from './start-routes/games_.umigame_.settings_.profile'
import { Route as GamesUmigameUUsernameRouteImport } from './start-routes/games_.umigame_.u_.$username'
import { Route as ApiUmigameCommentsIdReportRouteImport } from './start-routes/api_.umigame_.comments_.$id_.report'
import { Route as ApiUmigamePuzzlesIdCommentsRouteImport } from './start-routes/api_.umigame_.puzzles_.$id_.comments'
import { Route as ApiUmigamePuzzlesIdFavoriteRouteImport } from './start-routes/api_.umigame_.puzzles_.$id_.favorite'
import { Route as ApiUmigamePuzzlesIdSessionsRouteImport } from './start-routes/api_.umigame_.puzzles_.$id_.sessions'
import { Route as ApiUmigamePuzzlesIdVoteRouteImport } from './start-routes/api_.umigame_.puzzles_.$id_.vote'
import { Route as ApiUmigameSessionsIdGiveUpRouteImport } from './start-routes/api_.umigame_.sessions_.$id_.give-up'
import { Route as ApiUmigameSessionsIdGuessRouteImport } from './start-routes/api_.umigame_.sessions_.$id_.guess'
import { Route as ApiUmigameSessionsIdHintRouteImport } from './start-routes/api_.umigame_.sessions_.$id_.hint'
import { Route as ApiUmigameSessionsIdQuestionRouteImport } from './start-routes/api_.umigame_.sessions_.$id_.question'
import { Route as GamesUmigamePIdEditRouteImport } from './start-routes/games_.umigame_.p_.$id_.edit'
import { Route as GamesUmigamePIdPlayRouteImport } from './start-routes/games_.umigame_.p_.$id_.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeControlRoute = HomeControlRouteImport.update({
  id: '/home-control',
  path: '/home-control',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const WsolverRoute = WsolverRouteImport.update({
  id: '/wsolver',
  path: '/wsolver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJevRoute = ApiJevRouteImport.update({
  id: '/api_/jev',
  path: '/api/jev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNextRoute = ApiNextRouteImport.update({
  id: '/api_/next',
  path: '/api/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmanageRoute = ApiSmanageRouteImport.update({
  id: '/api_/smanage',
  path: '/api/smanage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth_/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameRoute = GamesUmigameRouteImport.update({
  id: '/games_/umigame',
  path: '/games/umigame',
  getParentRoute: () => rootRouteImport,
} as any)
const MapSplatRoute = MapSplatRouteImport.update({
  id: '/map_/$',
  path: '/map/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJevRoute = ToolsJevRouteImport.update({
  id: '/tools_/jev',
  path: '/tools/jev',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWsolverRoute = ToolsWsolverRouteImport.update({
  id: '/tools_/wsolver',
  path: '/tools/wsolver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordInteractionsRoute = ApiDiscordInteractionsRouteImport.update({
  id: '/api_/discord_/interactions',
  path: '/api/discord/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeShutdownRoute = ApiHomeShutdownRouteImport.update({
  id: '/api_/home_/shutdown',
  path: '/api/home/shutdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeStatusRoute = ApiHomeStatusRouteImport.update({
  id: '/api_/home_/status',
  path: '/api/home/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeWakeRoute = ApiHomeWakeRouteImport.update({
  id: '/api_/home_/wake',
  path: '/api/home/wake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJevLoginRoute = ApiJevLoginRouteImport.update({
  id: '/api_/jev_/login',
  path: '/api/jev/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcLinkCodesRoute = ApiMcLinkCodesRouteImport.update({
  id: '/api_/mc_/link-codes',
  path: '/api/mc/link-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcLinkStatusRoute = ApiMcLinkStatusRouteImport.update({
  id: '/api_/mc_/link-status',
  path: '/api/mc/link-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcStatusRoute = ApiMcStatusRouteImport.update({
  id: '/api_/mc_/status',
  path: '/api/mc/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcUnlinkRoute = ApiMcUnlinkRouteImport.update({
  id: '/api_/mc_/unlink',
  path: '/api/mc/unlink',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUmigamePuzzlesRoute = ApiUmigamePuzzlesRouteImport.update({
  id: '/api_/umigame_/puzzles',
  path: '/api/umigame/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccessLoginRoute = AuthAccessLoginRouteImport.update({
  id: '/auth_/access_/login',
  path: '/auth/access/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccessLogoutRoute = AuthAccessLogoutRouteImport.update({
  id: '/auth_/access_/logout',
  path: '/auth/access/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccessStartRoute = AuthAccessStartRouteImport.update({
  id: '/auth_/access_/start',
  path: '/auth/access/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth_/discord_/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordStartRoute = AuthDiscordStartRouteImport.update({
  id: '/auth_/discord_/start',
  path: '/auth/discord/start',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameAboutRoute = GamesUmigameAboutRouteImport.update({
  id: '/games_/umigame_/about',
  path: '/games/umigame/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameAdminRoute = GamesUmigameAdminRouteImport.update({
  id: '/games_/umigame_/admin',
  path: '/games/umigame/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameFavoritesRoute = GamesUmigameFavoritesRouteImport.update({
  id: '/games_/umigame_/favorites',
  path: '/games/umigame/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameLicensesRoute = GamesUmigameLicensesRouteImport.update({
  id: '/games_/umigame_/licenses',
  path: '/games/umigame/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameNewRoute = GamesUmigameNewRouteImport.update({
  id: '/games_/umigame_/new',
  path: '/games/umigame/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameRankingsRoute = GamesUmigameRankingsRouteImport.update({
  id: '/games_/umigame_/rankings',
  path: '/games/umigame/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameRecommendRoute = GamesUmigameRecommendRouteImport.update({
  id: '/games_/umigame_/recommend',
  path: '/games/umigame/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameResultsRoute = GamesUmigameResultsRouteImport.update({
  id: '/games_/umigame_/results',
  path: '/games/umigame/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUmigamePuzzlesIdRoute = ApiUmigamePuzzlesIdRouteImport.update({
  id: '/api_/umigame_/puzzles_/$id',
  path: '/api/umigame/puzzles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameAdminJevRoute = GamesUmigameAdminJevRouteImport.update({
  id: '/games_/umigame_/admin_/jev',
  path: '/games/umigame/admin/jev',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameAuthorQualityRoute =
  GamesUmigameAuthorQualityRouteImport.update({
    id: '/games_/umigame_/author_/quality',
    path: '/games/umigame/author/quality',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesUmigamePIdRoute = GamesUmigamePIdRouteImport.update({
  id: '/games_/umigame_/p_/$id',
  path: '/games/umigame/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigameSettingsProfileRoute =
  GamesUmigameSettingsProfileRouteImport.update({
    id: '/games_/umigame_/settings_/profile',
    path: '/games/umigame/settings/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesUmigameUUsernameRoute = GamesUmigameUUsernameRouteImport.update({
  id: '/games_/umigame_/u_/$username',
  path: '/games/umigame/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUmigameCommentsIdReportRoute =
  ApiUmigameCommentsIdReportRouteImport.update({
    id: '/api_/umigame_/comments_/$id_/report',
    path: '/api/umigame/comments/$id/report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUmigamePuzzlesIdCommentsRoute =
  ApiUmigamePuzzlesIdCommentsRouteImport.update({
    id: '/api_/umigame_/puzzles_/$id_/comments',
    path: '/api/umigame/puzzles/$id/comments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUmigamePuzzlesIdFavoriteRoute =
  ApiUmigamePuzzlesIdFavoriteRouteImport.update({
    id: '/api_/umigame_/puzzles_/$id_/favorite',
    path: '/api/umigame/puzzles/$id/favorite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUmigamePuzzlesIdSessionsRoute =
  ApiUmigamePuzzlesIdSessionsRouteImport.update({
    id: '/api_/umigame_/puzzles_/$id_/sessions',
    path: '/api/umigame/puzzles/$id/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUmigamePuzzlesIdVoteRoute = ApiUmigamePuzzlesIdVoteRouteImport.update({
  id: '/api_/umigame_/puzzles_/$id_/vote',
  path: '/api/umigame/puzzles/$id/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUmigameSessionsIdGiveUpRoute =
  ApiUmigameSessionsIdGiveUpRouteImport.update({
    id: '/api_/umigame_/sessions_/$id_/give-up',
    path: '/api/umigame/sessions/$id/give-up',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUmigameSessionsIdGuessRoute =
  ApiUmigameSessionsIdGuessRouteImport.update({
    id: '/api_/umigame_/sessions_/$id_/guess',
    path: '/api/umigame/sessions/$id/guess',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUmigameSessionsIdHintRoute =
  ApiUmigameSessionsIdHintRouteImport.update({
    id: '/api_/umigame_/sessions_/$id_/hint',
    path: '/api/umigame/sessions/$id/hint',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUmigameSessionsIdQuestionRoute =
  ApiUmigameSessionsIdQuestionRouteImport.update({
    id: '/api_/umigame_/sessions_/$id_/question',
    path: '/api/umigame/sessions/$id/question',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesUmigamePIdEditRoute = GamesUmigamePIdEditRouteImport.update({
  id: '/games_/umigame_/p_/$id_/edit',
  path: '/games/umigame/p/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUmigamePIdPlayRoute = GamesUmigamePIdPlayRouteImport.update({
  id: '/games_/umigame_/p_/$id_/play',
  path: '/games/umigame/p/$id/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/home-control': typeof HomeControlRoute
  '/licenses': typeof LicensesRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/wsolver': typeof WsolverRoute
  '/api/jev': typeof ApiJevRoute
  '/api/next': typeof ApiNextRoute
  '/api/smanage': typeof ApiSmanageRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/games/umigame': typeof GamesUmigameRoute
  '/map/$': typeof MapSplatRoute
  '/tools/jev': typeof ToolsJevRoute
  '/tools/wsolver': typeof ToolsWsolverRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/home/shutdown': typeof ApiHomeShutdownRoute
  '/api/home/status': typeof ApiHomeStatusRoute
  '/api/home/wake': typeof ApiHomeWakeRoute
  '/api/jev/login': typeof ApiJevLoginRoute
  '/api/mc/link-codes': typeof ApiMcLinkCodesRoute
  '/api/mc/link-status': typeof ApiMcLinkStatusRoute
  '/api/mc/status': typeof ApiMcStatusRoute
  '/api/mc/unlink': typeof ApiMcUnlinkRoute
  '/api/umigame/puzzles': typeof ApiUmigamePuzzlesRoute
  '/auth/access/login': typeof AuthAccessLoginRoute
  '/auth/access/logout': typeof AuthAccessLogoutRoute
  '/auth/access/start': typeof AuthAccessStartRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/start': typeof AuthDiscordStartRoute
  '/games/umigame/about': typeof GamesUmigameAboutRoute
  '/games/umigame/admin': typeof GamesUmigameAdminRoute
  '/games/umigame/favorites': typeof GamesUmigameFavoritesRoute
  '/games/umigame/licenses': typeof GamesUmigameLicensesRoute
  '/games/umigame/new': typeof GamesUmigameNewRoute
  '/games/umigame/rankings': typeof GamesUmigameRankingsRoute
  '/games/umigame/recommend': typeof GamesUmigameRecommendRoute
  '/games/umigame/results': typeof GamesUmigameResultsRoute
  '/api/umigame/puzzles/$id': typeof ApiUmigamePuzzlesIdRoute
  '/games/umigame/admin/jev': typeof GamesUmigameAdminJevRoute
  '/games/umigame/author/quality': typeof GamesUmigameAuthorQualityRoute
  '/games/umigame/p/$id': typeof GamesUmigamePIdRoute
  '/games/umigame/settings/profile': typeof GamesUmigameSettingsProfileRoute
  '/games/umigame/u/$username': typeof GamesUmigameUUsernameRoute
  '/api/umigame/comments/$id/report': typeof ApiUmigameCommentsIdReportRoute
  '/api/umigame/puzzles/$id/comments': typeof ApiUmigamePuzzlesIdCommentsRoute
  '/api/umigame/puzzles/$id/favorite': typeof ApiUmigamePuzzlesIdFavoriteRoute
  '/api/umigame/puzzles/$id/sessions': typeof ApiUmigamePuzzlesIdSessionsRoute
  '/api/umigame/puzzles/$id/vote': typeof ApiUmigamePuzzlesIdVoteRoute
  '/api/umigame/sessions/$id/give-up': typeof ApiUmigameSessionsIdGiveUpRoute
  '/api/umigame/sessions/$id/guess': typeof ApiUmigameSessionsIdGuessRoute
  '/api/umigame/sessions/$id/hint': typeof ApiUmigameSessionsIdHintRoute
  '/api/umigame/sessions/$id/question': typeof ApiUmigameSessionsIdQuestionRoute
  '/games/umigame/p/$id/edit': typeof GamesUmigamePIdEditRoute
  '/games/umigame/p/$id/play': typeof GamesUmigamePIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/home-control': typeof HomeControlRoute
  '/licenses': typeof LicensesRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/wsolver': typeof WsolverRoute
  '/api/jev': typeof ApiJevRoute
  '/api/next': typeof ApiNextRoute
  '/api/smanage': typeof ApiSmanageRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/games/umigame': typeof GamesUmigameRoute
  '/map/$': typeof MapSplatRoute
  '/tools/jev': typeof ToolsJevRoute
  '/tools/wsolver': typeof ToolsWsolverRoute
  '/api/discord/interactions': typeof ApiDiscordInteractionsRoute
  '/api/home/shutdown': typeof ApiHomeShutdownRoute
  '/api/home/status': typeof ApiHomeStatusRoute
  '/api/home/wake': typeof ApiHomeWakeRoute
  '/api/jev/login': typeof ApiJevLoginRoute
  '/api/mc/link-codes': typeof ApiMcLinkCodesRoute
  '/api/mc/link-status': typeof ApiMcLinkStatusRoute
  '/api/mc/status': typeof ApiMcStatusRoute
  '/api/mc/unlink': typeof ApiMcUnlinkRoute
  '/api/umigame/puzzles': typeof ApiUmigamePuzzlesRoute
  '/auth/access/login': typeof AuthAccessLoginRoute
  '/auth/access/logout': typeof AuthAccessLogoutRoute
  '/auth/access/start': typeof AuthAccessStartRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
  '/auth/discord/start': typeof AuthDiscordStartRoute
  '/games/umigame/about': typeof GamesUmigameAboutRoute
  '/games/umigame/admin': typeof GamesUmigameAdminRoute
  '/games/umigame/favorites': typeof GamesUmigameFavoritesRoute
  '/games/umigame/licenses': typeof GamesUmigameLicensesRoute
  '/games/umigame/new': typeof GamesUmigameNewRoute
  '/games/umigame/rankings': typeof GamesUmigameRankingsRoute
  '/games/umigame/recommend': typeof GamesUmigameRecommendRoute
  '/games/umigame/results': typeof GamesUmigameResultsRoute
  '/api/umigame/puzzles/$id': typeof ApiUmigamePuzzlesIdRoute
  '/games/umigame/admin/jev': typeof GamesUmigameAdminJevRoute
  '/games/umigame/author/quality': typeof GamesUmigameAuthorQualityRoute
  '/games/umigame/p/$id': typeof GamesUmigamePIdRoute
  '/games/umigame/settings/profile': typeof GamesUmigameSettingsProfileRoute
  '/games/umigame/u/$username': typeof GamesUmigameUUsernameRoute
  '/api/umigame/comments/$id/report': typeof ApiUmigameCommentsIdReportRoute
  '/api/umigame/puzzles/$id/comments': typeof ApiUmigamePuzzlesIdCommentsRoute
  '/api/umigame/puzzles/$id/favorite': typeof ApiUmigamePuzzlesIdFavoriteRoute
  '/api/umigame/puzzles/$id/sessions': typeof ApiUmigamePuzzlesIdSessionsRoute
  '/api/umigame/puzzles/$id/vote': typeof ApiUmigamePuzzlesIdVoteRoute
  '/api/umigame/sessions/$id/give-up': typeof ApiUmigameSessionsIdGiveUpRoute
  '/api/umigame/sessions/$id/guess': typeof ApiUmigameSessionsIdGuessRoute
  '/api/umigame/sessions/$id/hint': typeof ApiUmigameSessionsIdHintRoute
  '/api/umigame/sessions/$id/question': typeof ApiUmigameSessionsIdQuestionRoute
  '/games/umigame/p/$id/edit': typeof GamesUmigamePIdEditRoute
  '/games/umigame/p/$id/play': typeof GamesUmigamePIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRoute
  '/home-control': typeof HomeControlRoute
  '/licenses': typeof LicensesRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/wsolver': typeof WsolverRoute
  '/api_/jev': typeof ApiJevRoute
  '/api_/next': typeof ApiNextRoute
  '/api_/smanage': typeof ApiSmanageRoute
  '/auth_/logout': typeof AuthLogoutRoute
  '/games_/umigame': typeof GamesUmigameRoute
  '/map_/$': typeof MapSplatRoute
  '/tools_/jev': typeof ToolsJevRoute
  '/tools_/wsolver': typeof ToolsWsolverRoute
  '/api_/discord_/interactions': typeof ApiDiscordInteractionsRoute
  '/api_/home_/shutdown': typeof ApiHomeShutdownRoute
  '/api_/home_/status': typeof ApiHomeStatusRoute
  '/api_/home_/wake': typeof ApiHomeWakeRoute
  '/api_/jev_/login': typeof ApiJevLoginRoute
  '/api_/mc_/link-codes': typeof ApiMcLinkCodesRoute
  '/api_/mc_/link-status': typeof ApiMcLinkStatusRoute
  '/api_/mc_/status': typeof ApiMcStatusRoute
  '/api_/mc_/unlink': typeof ApiMcUnlinkRoute
  '/api_/umigame_/puzzles': typeof ApiUmigamePuzzlesRoute
  '/auth_/access_/login': typeof AuthAccessLoginRoute
  '/auth_/access_/logout': typeof AuthAccessLogoutRoute
  '/auth_/access_/start': typeof AuthAccessStartRoute
  '/auth_/discord_/callback': typeof AuthDiscordCallbackRoute
  '/auth_/discord_/start': typeof AuthDiscordStartRoute
  '/games_/umigame_/about': typeof GamesUmigameAboutRoute
  '/games_/umigame_/admin': typeof GamesUmigameAdminRoute
  '/games_/umigame_/favorites': typeof GamesUmigameFavoritesRoute
  '/games_/umigame_/licenses': typeof GamesUmigameLicensesRoute
  '/games_/umigame_/new': typeof GamesUmigameNewRoute
  '/games_/umigame_/rankings': typeof GamesUmigameRankingsRoute
  '/games_/umigame_/recommend': typeof GamesUmigameRecommendRoute
  '/games_/umigame_/results': typeof GamesUmigameResultsRoute
  '/api_/umigame_/puzzles_/$id': typeof ApiUmigamePuzzlesIdRoute
  '/games_/umigame_/admin_/jev': typeof GamesUmigameAdminJevRoute
  '/games_/umigame_/author_/quality': typeof GamesUmigameAuthorQualityRoute
  '/games_/umigame_/p_/$id': typeof GamesUmigamePIdRoute
  '/games_/umigame_/settings_/profile': typeof GamesUmigameSettingsProfileRoute
  '/games_/umigame_/u_/$username': typeof GamesUmigameUUsernameRoute
  '/api_/umigame_/comments_/$id_/report': typeof ApiUmigameCommentsIdReportRoute
  '/api_/umigame_/puzzles_/$id_/comments': typeof ApiUmigamePuzzlesIdCommentsRoute
  '/api_/umigame_/puzzles_/$id_/favorite': typeof ApiUmigamePuzzlesIdFavoriteRoute
  '/api_/umigame_/puzzles_/$id_/sessions': typeof ApiUmigamePuzzlesIdSessionsRoute
  '/api_/umigame_/puzzles_/$id_/vote': typeof ApiUmigamePuzzlesIdVoteRoute
  '/api_/umigame_/sessions_/$id_/give-up': typeof ApiUmigameSessionsIdGiveUpRoute
  '/api_/umigame_/sessions_/$id_/guess': typeof ApiUmigameSessionsIdGuessRoute
  '/api_/umigame_/sessions_/$id_/hint': typeof ApiUmigameSessionsIdHintRoute
  '/api_/umigame_/sessions_/$id_/question': typeof ApiUmigameSessionsIdQuestionRoute
  '/games_/umigame_/p_/$id_/edit': typeof GamesUmigamePIdEditRoute
  '/games_/umigame_/p_/$id_/play': typeof GamesUmigamePIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/apply'
    | '/contact'
    | '/games'
    | '/home-control'
    | '/licenses'
    | '/map'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/tools'
    | '/wsolver'
    | '/api/jev'
    | '/api/next'
    | '/api/smanage'
    | '/auth/logout'
    | '/games/umigame'
    | '/map/$'
    | '/tools/jev'
    | '/tools/wsolver'
    | '/api/discord/interactions'
    | '/api/home/shutdown'
    | '/api/home/status'
    | '/api/home/wake'
    | '/api/jev/login'
    | '/api/mc/link-codes'
    | '/api/mc/link-status'
    | '/api/mc/status'
    | '/api/mc/unlink'
    | '/api/umigame/puzzles'
    | '/auth/access/login'
    | '/auth/access/logout'
    | '/auth/access/start'
    | '/auth/discord/callback'
    | '/auth/discord/start'
    | '/games/umigame/about'
    | '/games/umigame/admin'
    | '/games/umigame/favorites'
    | '/games/umigame/licenses'
    | '/games/umigame/new'
    | '/games/umigame/rankings'
    | '/games/umigame/recommend'
    | '/games/umigame/results'
    | '/api/umigame/puzzles/$id'
    | '/games/umigame/admin/jev'
    | '/games/umigame/author/quality'
    | '/games/umigame/p/$id'
    | '/games/umigame/settings/profile'
    | '/games/umigame/u/$username'
    | '/api/umigame/comments/$id/report'
    | '/api/umigame/puzzles/$id/comments'
    | '/api/umigame/puzzles/$id/favorite'
    | '/api/umigame/puzzles/$id/sessions'
    | '/api/umigame/puzzles/$id/vote'
    | '/api/umigame/sessions/$id/give-up'
    | '/api/umigame/sessions/$id/guess'
    | '/api/umigame/sessions/$id/hint'
    | '/api/umigame/sessions/$id/question'
    | '/games/umigame/p/$id/edit'
    | '/games/umigame/p/$id/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/apply'
    | '/contact'
    | '/games'
    | '/home-control'
    | '/licenses'
    | '/map'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/tools'
    | '/wsolver'
    | '/api/jev'
    | '/api/next'
    | '/api/smanage'
    | '/auth/logout'
    | '/games/umigame'
    | '/map/$'
    | '/tools/jev'
    | '/tools/wsolver'
    | '/api/discord/interactions'
    | '/api/home/shutdown'
    | '/api/home/status'
    | '/api/home/wake'
    | '/api/jev/login'
    | '/api/mc/link-codes'
    | '/api/mc/link-status'
    | '/api/mc/status'
    | '/api/mc/unlink'
    | '/api/umigame/puzzles'
    | '/auth/access/login'
    | '/auth/access/logout'
    | '/auth/access/start'
    | '/auth/discord/callback'
    | '/auth/discord/start'
    | '/games/umigame/about'
    | '/games/umigame/admin'
    | '/games/umigame/favorites'
    | '/games/umigame/licenses'
    | '/games/umigame/new'
    | '/games/umigame/rankings'
    | '/games/umigame/recommend'
    | '/games/umigame/results'
    | '/api/umigame/puzzles/$id'
    | '/games/umigame/admin/jev'
    | '/games/umigame/author/quality'
    | '/games/umigame/p/$id'
    | '/games/umigame/settings/profile'
    | '/games/umigame/u/$username'
    | '/api/umigame/comments/$id/report'
    | '/api/umigame/puzzles/$id/comments'
    | '/api/umigame/puzzles/$id/favorite'
    | '/api/umigame/puzzles/$id/sessions'
    | '/api/umigame/puzzles/$id/vote'
    | '/api/umigame/sessions/$id/give-up'
    | '/api/umigame/sessions/$id/guess'
    | '/api/umigame/sessions/$id/hint'
    | '/api/umigame/sessions/$id/question'
    | '/games/umigame/p/$id/edit'
    | '/games/umigame/p/$id/play'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/apply'
    | '/contact'
    | '/games'
    | '/home-control'
    | '/licenses'
    | '/map'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/tools'
    | '/wsolver'
    | '/api_/jev'
    | '/api_/next'
    | '/api_/smanage'
    | '/auth_/logout'
    | '/games_/umigame'
    | '/map_/$'
    | '/tools_/jev'
    | '/tools_/wsolver'
    | '/api_/discord_/interactions'
    | '/api_/home_/shutdown'
    | '/api_/home_/status'
    | '/api_/home_/wake'
    | '/api_/jev_/login'
    | '/api_/mc_/link-codes'
    | '/api_/mc_/link-status'
    | '/api_/mc_/status'
    | '/api_/mc_/unlink'
    | '/api_/umigame_/puzzles'
    | '/auth_/access_/login'
    | '/auth_/access_/logout'
    | '/auth_/access_/start'
    | '/auth_/discord_/callback'
    | '/auth_/discord_/start'
    | '/games_/umigame_/about'
    | '/games_/umigame_/admin'
    | '/games_/umigame_/favorites'
    | '/games_/umigame_/licenses'
    | '/games_/umigame_/new'
    | '/games_/umigame_/rankings'
    | '/games_/umigame_/recommend'
    | '/games_/umigame_/results'
    | '/api_/umigame_/puzzles_/$id'
    | '/games_/umigame_/admin_/jev'
    | '/games_/umigame_/author_/quality'
    | '/games_/umigame_/p_/$id'
    | '/games_/umigame_/settings_/profile'
    | '/games_/umigame_/u_/$username'
    | '/api_/umigame_/comments_/$id_/report'
    | '/api_/umigame_/puzzles_/$id_/comments'
    | '/api_/umigame_/puzzles_/$id_/favorite'
    | '/api_/umigame_/puzzles_/$id_/sessions'
    | '/api_/umigame_/puzzles_/$id_/vote'
    | '/api_/umigame_/sessions_/$id_/give-up'
    | '/api_/umigame_/sessions_/$id_/guess'
    | '/api_/umigame_/sessions_/$id_/hint'
    | '/api_/umigame_/sessions_/$id_/question'
    | '/games_/umigame_/p_/$id_/edit'
    | '/games_/umigame_/p_/$id_/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  GamesRoute: typeof GamesRoute
  HomeControlRoute: typeof HomeControlRoute
  LicensesRoute: typeof LicensesRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  WsolverRoute: typeof WsolverRoute
  ApiJevRoute: typeof ApiJevRoute
  ApiNextRoute: typeof ApiNextRoute
  ApiSmanageRoute: typeof ApiSmanageRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  GamesUmigameRoute: typeof GamesUmigameRoute
  MapSplatRoute: typeof MapSplatRoute
  ToolsJevRoute: typeof ToolsJevRoute
  ToolsWsolverRoute: typeof ToolsWsolverRoute
  ApiDiscordInteractionsRoute: typeof ApiDiscordInteractionsRoute
  ApiHomeShutdownRoute: typeof ApiHomeShutdownRoute
  ApiHomeStatusRoute: typeof ApiHomeStatusRoute
  ApiHomeWakeRoute: typeof ApiHomeWakeRoute
  ApiJevLoginRoute: typeof ApiJevLoginRoute
  ApiMcLinkCodesRoute: typeof ApiMcLinkCodesRoute
  ApiMcLinkStatusRoute: typeof ApiMcLinkStatusRoute
  ApiMcStatusRoute: typeof ApiMcStatusRoute
  ApiMcUnlinkRoute: typeof ApiMcUnlinkRoute
  ApiUmigamePuzzlesRoute: typeof ApiUmigamePuzzlesRoute
  AuthAccessLoginRoute: typeof AuthAccessLoginRoute
  AuthAccessLogoutRoute: typeof AuthAccessLogoutRoute
  AuthAccessStartRoute: typeof AuthAccessStartRoute
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
  AuthDiscordStartRoute: typeof AuthDiscordStartRoute
  GamesUmigameAboutRoute: typeof GamesUmigameAboutRoute
  GamesUmigameAdminRoute: typeof GamesUmigameAdminRoute
  GamesUmigameFavoritesRoute: typeof GamesUmigameFavoritesRoute
  GamesUmigameLicensesRoute: typeof GamesUmigameLicensesRoute
  GamesUmigameNewRoute: typeof GamesUmigameNewRoute
  GamesUmigameRankingsRoute: typeof GamesUmigameRankingsRoute
  GamesUmigameRecommendRoute: typeof GamesUmigameRecommendRoute
  GamesUmigameResultsRoute: typeof GamesUmigameResultsRoute
  ApiUmigamePuzzlesIdRoute: typeof ApiUmigamePuzzlesIdRoute
  GamesUmigameAdminJevRoute: typeof GamesUmigameAdminJevRoute
  GamesUmigameAuthorQualityRoute: typeof GamesUmigameAuthorQualityRoute
  GamesUmigamePIdRoute: typeof GamesUmigamePIdRoute
  GamesUmigameSettingsProfileRoute: typeof GamesUmigameSettingsProfileRoute
  GamesUmigameUUsernameRoute: typeof GamesUmigameUUsernameRoute
  ApiUmigameCommentsIdReportRoute: typeof ApiUmigameCommentsIdReportRoute
  ApiUmigamePuzzlesIdCommentsRoute: typeof ApiUmigamePuzzlesIdCommentsRoute
  ApiUmigamePuzzlesIdFavoriteRoute: typeof ApiUmigamePuzzlesIdFavoriteRoute
  ApiUmigamePuzzlesIdSessionsRoute: typeof ApiUmigamePuzzlesIdSessionsRoute
  ApiUmigamePuzzlesIdVoteRoute: typeof ApiUmigamePuzzlesIdVoteRoute
  ApiUmigameSessionsIdGiveUpRoute: typeof ApiUmigameSessionsIdGiveUpRoute
  ApiUmigameSessionsIdGuessRoute: typeof ApiUmigameSessionsIdGuessRoute
  ApiUmigameSessionsIdHintRoute: typeof ApiUmigameSessionsIdHintRoute
  ApiUmigameSessionsIdQuestionRoute: typeof ApiUmigameSessionsIdQuestionRoute
  GamesUmigamePIdEditRoute: typeof GamesUmigamePIdEditRoute
  GamesUmigamePIdPlayRoute: typeof GamesUmigamePIdPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-control': {
      id: '/home-control'
      path: '/home-control'
      fullPath: '/home-control'
      preLoaderRoute: typeof HomeControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wsolver': {
      id: '/wsolver'
      path: '/wsolver'
      fullPath: '/wsolver'
      preLoaderRoute: typeof WsolverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/jev': {
      id: '/api_/jev'
      path: '/api/jev'
      fullPath: '/api/jev'
      preLoaderRoute: typeof ApiJevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/next': {
      id: '/api_/next'
      path: '/api/next'
      fullPath: '/api/next'
      preLoaderRoute: typeof ApiNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/smanage': {
      id: '/api_/smanage'
      path: '/api/smanage'
      fullPath: '/api/smanage'
      preLoaderRoute: typeof ApiSmanageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/logout': {
      id: '/auth_/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame': {
      id: '/games_/umigame'
      path: '/games/umigame'
      fullPath: '/games/umigame'
      preLoaderRoute: typeof GamesUmigameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map_/$': {
      id: '/map_/$'
      path: '/map/$'
      fullPath: '/map/$'
      preLoaderRoute: typeof MapSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools_/jev': {
      id: '/tools_/jev'
      path: '/tools/jev'
      fullPath: '/tools/jev'
      preLoaderRoute: typeof ToolsJevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools_/wsolver': {
      id: '/tools_/wsolver'
      path: '/tools/wsolver'
      fullPath: '/tools/wsolver'
      preLoaderRoute: typeof ToolsWsolverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/discord_/interactions': {
      id: '/api_/discord_/interactions'
      path: '/api/discord/interactions'
      fullPath: '/api/discord/interactions'
      preLoaderRoute: typeof ApiDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/home_/shutdown': {
      id: '/api_/home_/shutdown'
      path: '/api/home/shutdown'
      fullPath: '/api/home/shutdown'
      preLoaderRoute: typeof ApiHomeShutdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/home_/status': {
      id: '/api_/home_/status'
      path: '/api/home/status'
      fullPath: '/api/home/status'
      preLoaderRoute: typeof ApiHomeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/home_/wake': {
      id: '/api_/home_/wake'
      path: '/api/home/wake'
      fullPath: '/api/home/wake'
      preLoaderRoute: typeof ApiHomeWakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/jev_/login': {
      id: '/api_/jev_/login'
      path: '/api/jev/login'
      fullPath: '/api/jev/login'
      preLoaderRoute: typeof ApiJevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/mc_/link-codes': {
      id: '/api_/mc_/link-codes'
      path: '/api/mc/link-codes'
      fullPath: '/api/mc/link-codes'
      preLoaderRoute: typeof ApiMcLinkCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/mc_/link-status': {
      id: '/api_/mc_/link-status'
      path: '/api/mc/link-status'
      fullPath: '/api/mc/link-status'
      preLoaderRoute: typeof ApiMcLinkStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/mc_/status': {
      id: '/api_/mc_/status'
      path: '/api/mc/status'
      fullPath: '/api/mc/status'
      preLoaderRoute: typeof ApiMcStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/mc_/unlink': {
      id: '/api_/mc_/unlink'
      path: '/api/mc/unlink'
      fullPath: '/api/mc/unlink'
      preLoaderRoute: typeof ApiMcUnlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/puzzles': {
      id: '/api_/umigame_/puzzles'
      path: '/api/umigame/puzzles'
      fullPath: '/api/umigame/puzzles'
      preLoaderRoute: typeof ApiUmigamePuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/access_/login': {
      id: '/auth_/access_/login'
      path: '/auth/access/login'
      fullPath: '/auth/access/login'
      preLoaderRoute: typeof AuthAccessLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/access_/logout': {
      id: '/auth_/access_/logout'
      path: '/auth/access/logout'
      fullPath: '/auth/access/logout'
      preLoaderRoute: typeof AuthAccessLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/access_/start': {
      id: '/auth_/access_/start'
      path: '/auth/access/start'
      fullPath: '/auth/access/start'
      preLoaderRoute: typeof AuthAccessStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/discord_/callback': {
      id: '/auth_/discord_/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/discord_/start': {
      id: '/auth_/discord_/start'
      path: '/auth/discord/start'
      fullPath: '/auth/discord/start'
      preLoaderRoute: typeof AuthDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/about': {
      id: '/games_/umigame_/about'
      path: '/games/umigame/about'
      fullPath: '/games/umigame/about'
      preLoaderRoute: typeof GamesUmigameAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/admin': {
      id: '/games_/umigame_/admin'
      path: '/games/umigame/admin'
      fullPath: '/games/umigame/admin'
      preLoaderRoute: typeof GamesUmigameAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/favorites': {
      id: '/games_/umigame_/favorites'
      path: '/games/umigame/favorites'
      fullPath: '/games/umigame/favorites'
      preLoaderRoute: typeof GamesUmigameFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/licenses': {
      id: '/games_/umigame_/licenses'
      path: '/games/umigame/licenses'
      fullPath: '/games/umigame/licenses'
      preLoaderRoute: typeof GamesUmigameLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/new': {
      id: '/games_/umigame_/new'
      path: '/games/umigame/new'
      fullPath: '/games/umigame/new'
      preLoaderRoute: typeof GamesUmigameNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/rankings': {
      id: '/games_/umigame_/rankings'
      path: '/games/umigame/rankings'
      fullPath: '/games/umigame/rankings'
      preLoaderRoute: typeof GamesUmigameRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/recommend': {
      id: '/games_/umigame_/recommend'
      path: '/games/umigame/recommend'
      fullPath: '/games/umigame/recommend'
      preLoaderRoute: typeof GamesUmigameRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/results': {
      id: '/games_/umigame_/results'
      path: '/games/umigame/results'
      fullPath: '/games/umigame/results'
      preLoaderRoute: typeof GamesUmigameResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/puzzles_/$id': {
      id: '/api_/umigame_/puzzles_/$id'
      path: '/api/umigame/puzzles/$id'
      fullPath: '/api/umigame/puzzles/$id'
      preLoaderRoute: typeof ApiUmigamePuzzlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/admin_/jev': {
      id: '/games_/umigame_/admin_/jev'
      path: '/games/umigame/admin/jev'
      fullPath: '/games/umigame/admin/jev'
      preLoaderRoute: typeof GamesUmigameAdminJevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/author_/quality': {
      id: '/games_/umigame_/author_/quality'
      path: '/games/umigame/author/quality'
      fullPath: '/games/umigame/author/quality'
      preLoaderRoute: typeof GamesUmigameAuthorQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/p_/$id': {
      id: '/games_/umigame_/p_/$id'
      path: '/games/umigame/p/$id'
      fullPath: '/games/umigame/p/$id'
      preLoaderRoute: typeof GamesUmigamePIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/settings_/profile': {
      id: '/games_/umigame_/settings_/profile'
      path: '/games/umigame/settings/profile'
      fullPath: '/games/umigame/settings/profile'
      preLoaderRoute: typeof GamesUmigameSettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/u_/$username': {
      id: '/games_/umigame_/u_/$username'
      path: '/games/umigame/u/$username'
      fullPath: '/games/umigame/u/$username'
      preLoaderRoute: typeof GamesUmigameUUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/comments_/$id_/report': {
      id: '/api_/umigame_/comments_/$id_/report'
      path: '/api/umigame/comments/$id/report'
      fullPath: '/api/umigame/comments/$id/report'
      preLoaderRoute: typeof ApiUmigameCommentsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/puzzles_/$id_/comments': {
      id: '/api_/umigame_/puzzles_/$id_/comments'
      path: '/api/umigame/puzzles/$id/comments'
      fullPath: '/api/umigame/puzzles/$id/comments'
      preLoaderRoute: typeof ApiUmigamePuzzlesIdCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/puzzles_/$id_/favorite': {
      id: '/api_/umigame_/puzzles_/$id_/favorite'
      path: '/api/umigame/puzzles/$id/favorite'
      fullPath: '/api/umigame/puzzles/$id/favorite'
      preLoaderRoute: typeof ApiUmigamePuzzlesIdFavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/puzzles_/$id_/sessions': {
      id: '/api_/umigame_/puzzles_/$id_/sessions'
      path: '/api/umigame/puzzles/$id/sessions'
      fullPath: '/api/umigame/puzzles/$id/sessions'
      preLoaderRoute: typeof ApiUmigamePuzzlesIdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/puzzles_/$id_/vote': {
      id: '/api_/umigame_/puzzles_/$id_/vote'
      path: '/api/umigame/puzzles/$id/vote'
      fullPath: '/api/umigame/puzzles/$id/vote'
      preLoaderRoute: typeof ApiUmigamePuzzlesIdVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/sessions_/$id_/give-up': {
      id: '/api_/umigame_/sessions_/$id_/give-up'
      path: '/api/umigame/sessions/$id/give-up'
      fullPath: '/api/umigame/sessions/$id/give-up'
      preLoaderRoute: typeof ApiUmigameSessionsIdGiveUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/sessions_/$id_/guess': {
      id: '/api_/umigame_/sessions_/$id_/guess'
      path: '/api/umigame/sessions/$id/guess'
      fullPath: '/api/umigame/sessions/$id/guess'
      preLoaderRoute: typeof ApiUmigameSessionsIdGuessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/sessions_/$id_/hint': {
      id: '/api_/umigame_/sessions_/$id_/hint'
      path: '/api/umigame/sessions/$id/hint'
      fullPath: '/api/umigame/sessions/$id/hint'
      preLoaderRoute: typeof ApiUmigameSessionsIdHintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api_/umigame_/sessions_/$id_/question': {
      id: '/api_/umigame_/sessions_/$id_/question'
      path: '/api/umigame/sessions/$id/question'
      fullPath: '/api/umigame/sessions/$id/question'
      preLoaderRoute: typeof ApiUmigameSessionsIdQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/p_/$id_/edit': {
      id: '/games_/umigame_/p_/$id_/edit'
      path: '/games/umigame/p/$id/edit'
      fullPath: '/games/umigame/p/$id/edit'
      preLoaderRoute: typeof GamesUmigamePIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/umigame_/p_/$id_/play': {
      id: '/games_/umigame_/p_/$id_/play'
      path: '/games/umigame/p/$id/play'
      fullPath: '/games/umigame/p/$id/play'
      preLoaderRoute: typeof GamesUmigamePIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  GamesRoute: GamesRoute,
  HomeControlRoute: HomeControlRoute,
  LicensesRoute: LicensesRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  WsolverRoute: WsolverRoute,
  ApiJevRoute: ApiJevRoute,
  ApiNextRoute: ApiNextRoute,
  ApiSmanageRoute: ApiSmanageRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  GamesUmigameRoute: GamesUmigameRoute,
  MapSplatRoute: MapSplatRoute,
  ToolsJevRoute: ToolsJevRoute,
  ToolsWsolverRoute: ToolsWsolverRoute,
  ApiDiscordInteractionsRoute: ApiDiscordInteractionsRoute,
  ApiHomeShutdownRoute: ApiHomeShutdownRoute,
  ApiHomeStatusRoute: ApiHomeStatusRoute,
  ApiHomeWakeRoute: ApiHomeWakeRoute,
  ApiJevLoginRoute: ApiJevLoginRoute,
  ApiMcLinkCodesRoute: ApiMcLinkCodesRoute,
  ApiMcLinkStatusRoute: ApiMcLinkStatusRoute,
  ApiMcStatusRoute: ApiMcStatusRoute,
  ApiMcUnlinkRoute: ApiMcUnlinkRoute,
  ApiUmigamePuzzlesRoute: ApiUmigamePuzzlesRoute,
  AuthAccessLoginRoute: AuthAccessLoginRoute,
  AuthAccessLogoutRoute: AuthAccessLogoutRoute,
  AuthAccessStartRoute: AuthAccessStartRoute,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
  AuthDiscordStartRoute: AuthDiscordStartRoute,
  GamesUmigameAboutRoute: GamesUmigameAboutRoute,
  GamesUmigameAdminRoute: GamesUmigameAdminRoute,
  GamesUmigameFavoritesRoute: GamesUmigameFavoritesRoute,
  GamesUmigameLicensesRoute: GamesUmigameLicensesRoute,
  GamesUmigameNewRoute: GamesUmigameNewRoute,
  GamesUmigameRankingsRoute: GamesUmigameRankingsRoute,
  GamesUmigameRecommendRoute: GamesUmigameRecommendRoute,
  GamesUmigameResultsRoute: GamesUmigameResultsRoute,
  ApiUmigamePuzzlesIdRoute: ApiUmigamePuzzlesIdRoute,
  GamesUmigameAdminJevRoute: GamesUmigameAdminJevRoute,
  GamesUmigameAuthorQualityRoute: GamesUmigameAuthorQualityRoute,
  GamesUmigamePIdRoute: GamesUmigamePIdRoute,
  GamesUmigameSettingsProfileRoute: GamesUmigameSettingsProfileRoute,
  GamesUmigameUUsernameRoute: GamesUmigameUUsernameRoute,
  ApiUmigameCommentsIdReportRoute: ApiUmigameCommentsIdReportRoute,
  ApiUmigamePuzzlesIdCommentsRoute: ApiUmigamePuzzlesIdCommentsRoute,
  ApiUmigamePuzzlesIdFavoriteRoute: ApiUmigamePuzzlesIdFavoriteRoute,
  ApiUmigamePuzzlesIdSessionsRoute: ApiUmigamePuzzlesIdSessionsRoute,
  ApiUmigamePuzzlesIdVoteRoute: ApiUmigamePuzzlesIdVoteRoute,
  ApiUmigameSessionsIdGiveUpRoute: ApiUmigameSessionsIdGiveUpRoute,
  ApiUmigameSessionsIdGuessRoute: ApiUmigameSessionsIdGuessRoute,
  ApiUmigameSessionsIdHintRoute: ApiUmigameSessionsIdHintRoute,
  ApiUmigameSessionsIdQuestionRoute: ApiUmigameSessionsIdQuestionRoute,
  GamesUmigamePIdEditRoute: GamesUmigamePIdEditRoute,
  GamesUmigamePIdPlayRoute: GamesUmigamePIdPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
